41.162.76.170  	ERROR	Thread-9	[G373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
41.162.76.170  	ERROR	Thread-8	[F373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
41.162.76.170  	ERROR	Thread-4	[B373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
41.162.76.170  	ERROR	Thread-5	[C373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
41.162.76.170  	ERROR	Thread-12	[J373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
41.162.76.170  	ERROR	Thread-7	[E373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
41.162.76.170  	ERROR	Thread-6	[D373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
148.251.132.84 	ERROR	Thread-25	[G373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-21	[C373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-20	[B373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-26	[H373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-30	[L373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-27	[I373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-23	[E373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-29	[K373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-33	[O373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-24	[F373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-28	[J373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-32	[N373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-34	[P373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-35	[Q373010]	'csrftoken'
148.251.132.84 	ERROR	Thread-31	[M373010]	'csrftoken'
41.162.76.170  	ERROR	Thread-19	[Q373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE64846D8>, 'Connection to 41.162.76.170 timed out. (connect timeout=5)'))
41.162.76.170  	ERROR	Thread-13	[K373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE54D0A20>, 'Connection to 41.162.76.170 timed out. (connect timeout=5)'))
41.162.76.170  	ERROR	Thread-15	[M373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE647A5C0>, 'Connection to 41.162.76.170 timed out. (connect timeout=5)'))
67.205.147.16  	ERROR	Thread-37	[C373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-40	[F373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-36	[B373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-41	[G373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-39	[E373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-42	[H373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-38	[D373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
148.251.132.84 	ERROR	Thread-22	[D373010]	'csrftoken'
67.205.147.16  	ERROR	Thread-44	[J373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-45	[K373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-43	[I373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-46	[L373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
41.162.76.170  	ERROR	Thread-16	[N373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
67.205.147.16  	ERROR	Thread-48	[N373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-47	[M373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-51	[Q373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-49	[O373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.147.16  	ERROR	Thread-50	[P373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
41.162.76.170  	ERROR	Thread-17	[O373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
67.205.146.182 	ERROR	Thread-53	[C373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-55	[E373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-56	[F373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-60	[J373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-58	[H373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-57	[G373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-59	[I373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-61	[K373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-64	[O373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-63	[N373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-52	[B373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-62	[M373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-66	[Q373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-65	[P373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-67	[R373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.182 	ERROR	Thread-54	[D373010]	Expecting value: line 1 column 1 (char 0)
41.162.76.170  	ERROR	Thread-18	[P373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE69F8048>, 'Connection to 41.162.76.170 timed out. (connect timeout=5)'))
41.162.76.170  	ERROR	Thread-10	[H373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE54D0390>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
218.48.229.173 	ERROR	Thread-69	[C373010]	Expecting value: line 1 column 1 (char 0)
218.48.229.173 	ERROR	Thread-68	[B373010]	[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2292)
178.132.216.115	ERROR	Thread-96	[Q373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
218.48.229.173 	ERROR	Thread-71	[E373010]	Expecting value: line 1 column 1 (char 0)
218.48.229.173 	ERROR	Thread-76	[K373010]	Expecting value: line 1 column 1 (char 0)
218.48.229.173 	ERROR	Thread-80	[P373010]	[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2292)
218.48.229.173 	ERROR	Thread-79	[O373010]	[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2292)
218.48.229.173 	ERROR	Thread-74	[H373010]	Expecting value: line 1 column 1 (char 0)
178.132.216.115	ERROR	Thread-92	[M373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
178.132.216.115	ERROR	Thread-94	[O373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
218.48.229.173 	ERROR	Thread-82	[R373010]	Expecting value: line 1 column 1 (char 0)
218.48.229.173 	ERROR	Thread-75	[J373010]	Expecting value: line 1 column 1 (char 0)
67.205.151.39  	ERROR	Thread-118	[J373010]	Expecting value: line 1 column 1 (char 0)
67.205.151.39  	ERROR	Thread-115	[C373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
131.153.48.27  	ERROR	Thread-100	[E373010]	Expecting value: line 1 column 1 (char 0)
131.153.48.27  	ERROR	Thread-101	[H373010]	Expecting value: line 1 column 1 (char 0)
131.153.48.27  	ERROR	Thread-103	[K373010]	Expecting value: line 1 column 1 (char 0)
131.153.48.27  	ERROR	Thread-102	[J373010]	Expecting value: line 1 column 1 (char 0)
131.153.48.27  	ERROR	Thread-104	[O373010]	Expecting value: line 1 column 1 (char 0)
131.153.48.27  	ERROR	Thread-99	[C373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
131.153.48.27  	ERROR	Thread-109	[E373010]	Expecting value: line 1 column 1 (char 0)
67.205.151.39  	ERROR	Thread-126	[C373010]	Expecting value: line 1 column 1 (char 0)
131.153.48.27  	ERROR	Thread-113	[O373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
67.205.145.208 	ERROR	Thread-129	[J373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.208 	ERROR	Thread-128	[C373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.208 	ERROR	Thread-130	[C373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.208 	ERROR	Thread-138	[Z373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.208 	ERROR	Thread-136	[X373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.208 	ERROR	Thread-140	[A383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.208 	ERROR	Thread-133	[U373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.208 	ERROR	Thread-141	[B383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.208 	ERROR	Thread-132	[T373010]	Expecting value: line 1 column 1 (char 0)
67.205.145.208 	ERROR	Thread-143	[D383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.51  	ERROR	Thread-144	[T373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.51  	ERROR	Thread-145	[U373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.51  	ERROR	Thread-149	[B383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.51  	ERROR	Thread-147	[Z373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.51  	ERROR	Thread-151	[E383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
178.132.216.115	ERROR	Thread-97	[R373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DEA04DC50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
67.205.145.51  	ERROR	Thread-157	[Z373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.51  	ERROR	Thread-158	[B383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.51  	ERROR	Thread-155	[T373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.145.51  	ERROR	Thread-159	[E383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
131.153.48.27  	ERROR	Thread-105	[P373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
131.153.48.27  	ERROR	Thread-108	[C373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
131.153.48.27  	ERROR	Thread-110	[H373010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
159.65.97.110  	ERROR	Thread-163	[B383010]	Expecting value: line 1 column 1 (char 0)
159.65.97.110  	ERROR	Thread-161	[U373010]	Expecting value: line 1 column 1 (char 0)
159.65.97.110  	ERROR	Thread-167	[E383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
159.65.97.110  	ERROR	Thread-169	[B383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
159.65.97.110  	ERROR	Thread-170	[E383010]	Expecting value: line 1 column 1 (char 0)
159.65.97.110  	ERROR	Thread-168	[Z373010]	Expecting value: line 1 column 1 (char 0)
159.65.97.110  	ERROR	Thread-164	[T373010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.26  	ERROR	Thread-173	[E383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
159.65.97.110  	ERROR	Thread-171	[E383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.26  	ERROR	Thread-175	[E383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.26  	ERROR	Thread-174	[E383010]	Expecting value: line 1 column 1 (char 0)
159.65.97.110  	ERROR	Thread-172	[E383010]	Expecting value: line 1 column 1 (char 0)
67.205.146.26  	ERROR	Thread-176	[E383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.26  	ERROR	Thread-177	[E383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.26  	ERROR	Thread-178	[E383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
67.205.146.26  	ERROR	Thread-179	[E383010]	("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
171.255.192.118	ERROR	Thread-180	[E383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
171.255.192.118	ERROR	Thread-181	[E383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
171.255.192.118	ERROR	Thread-182	[E383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
171.255.192.118	ERROR	Thread-183	[E383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
171.255.192.118	ERROR	Thread-184	[E383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
171.255.192.118	ERROR	Thread-185	[E383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
171.255.192.118	ERROR	Thread-186	[E383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
197.254.80.94  	ERROR	Thread-189	[E383010]	Expecting value: line 1 column 1 (char 0)
195.16.77.42   	ERROR	Thread-188	[E383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DEA0565C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
95.79.28.168   	ERROR	Thread-217	[X383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE47514A8>, 'Connection to 95.79.28.168 timed out. (connect timeout=5)'))
95.79.28.168   	ERROR	Thread-215	[V383010]	Expecting value: line 1 column 1 (char 0)
160.238.136.121	ERROR	Thread-226	[Y383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE73F9DA0>, 'Connection to 160.238.136.121 timed out. (connect timeout=5)'))
131.0.246.157  	ERROR	Thread-245	[G393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
131.0.246.157  	ERROR	Thread-242	[D393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
131.0.246.157  	ERROR	Thread-244	[F393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
160.238.136.121	ERROR	Thread-232	[A393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
160.238.136.121	ERROR	Thread-223	[X383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE48DEA90>, 'Connection to 160.238.136.121 timed out. (connect timeout=5)'))
160.238.136.121	ERROR	Thread-225	[X383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE73F9278>, 'Connection to 160.238.136.121 timed out. (connect timeout=5)'))
160.238.136.121	ERROR	Thread-222	[Y383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE415DDD8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
160.238.136.121	ERROR	Thread-221	[X383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE490CF98>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
160.238.136.121	ERROR	Thread-224	[Y383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE48E3DD8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
191.240.154.246	ERROR	Thread-259	[E393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
191.240.154.246	ERROR	Thread-258	[D393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
160.238.136.121	ERROR	Thread-228	[X383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE73F9400>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
160.238.136.121	ERROR	Thread-229	[X383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE54B8CF8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
160.238.136.121	ERROR	Thread-231	[383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE73E6898>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
160.238.136.121	ERROR	Thread-233	[B393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE54DBE10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
160.238.136.121	ERROR	Thread-230	[Z383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE73E6F60>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
160.238.136.121	ERROR	Thread-234	[C393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE54DB7F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
160.238.136.121	ERROR	Thread-236	[E393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE54DB2B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
191.240.154.246	ERROR	Thread-253	[Z383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
131.0.246.157  	ERROR	Thread-237	[Z383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE647A6A0>, 'Connection to 131.0.246.157 timed out. (connect timeout=5)'))
195.210.172.43 	ERROR	Thread-287	[M393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
191.240.154.246	ERROR	Thread-267	[N393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
195.210.172.43 	ERROR	Thread-283	[H393010]	Expecting value: line 1 column 1 (char 0)
195.210.172.43 	ERROR	Thread-281	[F393010]	Expecting value: line 1 column 1 (char 0)
195.210.172.43 	ERROR	Thread-280	[B393010]	Expecting value: line 1 column 1 (char 0)
195.210.172.43 	ERROR	Thread-279	[Z383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
195.210.172.43 	ERROR	Thread-285	[K393010]	Expecting value: line 1 column 1 (char 0)
131.0.246.157  	ERROR	Thread-240	[B393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE73F5C50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
131.0.246.157  	ERROR	Thread-246	[H393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE73E3588>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
131.0.246.157  	ERROR	Thread-247	[I393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE7405438>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
131.0.246.157  	ERROR	Thread-251	[M393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE7403DA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
131.0.246.157  	ERROR	Thread-250	[L393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE887D208>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
131.0.246.157  	ERROR	Thread-249	[K393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE74036A0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
195.210.172.43 	ERROR	Thread-284	[I393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
191.240.154.246	ERROR	Thread-255	[A393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE64847B8>, 'Connection to 191.240.154.246 timed out. (connect timeout=5)'))
195.210.172.43 	ERROR	Thread-282	[G393010]	Expecting value: line 1 column 1 (char 0)
195.210.172.43 	ERROR	Thread-286	[L393010]	Expecting value: line 1 column 1 (char 0)
191.240.154.246	ERROR	Thread-261	[G393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE8870BA8>, 'Connection to 191.240.154.246 timed out. (connect timeout=5)'))
12.8.187.125   	ERROR	Thread-269	[Z383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
12.8.187.125   	ERROR	Thread-272	[G393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
87.204.246.1   	ERROR	Thread-305	[M393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
87.204.246.1   	ERROR	Thread-299	[B393010]	'csrftoken'
87.204.246.1   	ERROR	Thread-298	[Z383010]	'csrftoken'
87.204.246.1   	ERROR	Thread-300	[G393010]	'csrftoken'
87.204.246.1   	ERROR	Thread-301	[H393010]	'csrftoken'
87.204.246.1   	ERROR	Thread-302	[I393010]	'csrftoken'
87.204.246.1   	ERROR	Thread-303	[K393010]	'csrftoken'
87.204.246.1   	ERROR	Thread-304	[L393010]	'csrftoken'
12.8.187.125   	ERROR	Thread-277	[M393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
191.240.154.246	ERROR	Thread-254	[383010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DEA056C88>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
191.240.154.246	ERROR	Thread-257	[C393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE88AFB00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
191.240.154.246	ERROR	Thread-256	[B393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE889EB00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
191.240.154.246	ERROR	Thread-260	[F393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE889BDA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
191.240.154.246	ERROR	Thread-263	[I393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE887D390>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
191.240.154.246	ERROR	Thread-262	[H393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE415DE48>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
191.240.154.246	ERROR	Thread-266	[M393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE887DDD8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
103.214.202.185	ERROR	Thread-292	[G393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
103.214.202.185	ERROR	Thread-294	[I393010]	Expecting value: line 1 column 1 (char 0)
103.214.202.185	ERROR	Thread-296	[L393010]	Expecting value: line 1 column 1 (char 0)
12.8.187.125   	ERROR	Thread-270	[B393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE54C5828>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
12.8.187.125   	ERROR	Thread-273	[H393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE48F8160>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
12.8.187.125   	ERROR	Thread-276	[L393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DE88AF9B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
103.214.202.185	ERROR	Thread-290	[B393010]	Expecting value: line 1 column 1 (char 0)
12.8.187.125   	ERROR	Thread-275	[K393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DEA042AC8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
12.8.187.125   	ERROR	Thread-278	[O393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000004DEA05D5F8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))
103.214.202.185	ERROR	Thread-295	[K393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ajax/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
94.143.172.42  	ERROR	Thread-326	[Z383010]	'csrftoken'
94.143.172.42  	ERROR	Thread-327	[B393010]	'csrftoken'
94.143.172.42  	ERROR	Thread-328	[G393010]	'csrftoken'
117.121.207.149	ERROR	Thread-308	[G393010]	HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
103.214.202.185	ERROR	Thread-289	[Z383010]	Expecting value: line 1 column 1 (char 0)
94.143.172.42  	ERROR	Thread-329	[Z383010]	'csrftoken'
94.143.172.42  	ERROR	Thread-332	[Z383010]	'csrftoken'
94.143.172.42  	ERROR	Thread-333	[B393010]	'csrftoken'
